### ISSUE TITLE
User list in config file not working

### ISSUE THREAD

**Issue by pavpanchekha** [sampsyo/hooknook#10]
I can put a Python list in the configuration file, but it still doesn't work. I'm setting users on the command line, but it'd be better to avoid this.

**Comment by sampsyo** [comment]
Hmm; it's working with our setup, where the config looks like this: 

    USERS = ['sampsyo', 'uwsampa', 'bholt', 'jamesbornholt']

That's not doing it for you (neither for the web login nor for whitelisting the allowed repositories)?

**Comment by pavpanchekha** [comment]
Yep, I added

    USERS = ['sampsyo', 'uwsampa', 'bholt', 'jamesbornholt']

to my config, but it won't let me in to the web login. I've got a script that starts it with the right flags, so it's not urgent, but it sure would be good to know what's borked.

**Comment by sampsyo** [comment]
Oh! I see the problem. The command-line flags are overriding the configuration [in `run`](https://github.com/sampsyo/hooknook/blob/master/hooknook.py#L380), so the config is getting (mostly) ignored. Oops. I didn't notice because I'm running Hooknook with a separate HTTP server (Gunicorn) instead of the built-in Flask one, so I'm bypassing the `run` function altogether.

I'll fix this up.

**Comment by pavpanchekha** [comment]
Thanks!

**Comment by sampsyo** [comment]
That should do it! :sparkles:
