### ISSUE TITLE
Authentication is broken

### ISSUE THREAD

**Issue by jamesbornholt** [sampsyo/hooknook#9]
There's a bug in the authentication logic -- I think you need to delete [line 307](https://github.com/sampsyo/hooknook/blob/master/hooknook.py#L307) in hooknook.py (duplicates [line 318](https://github.com/sampsyo/hooknook/blob/master/hooknook.py#L318)). Right now, the github_token session variable gets set even if a user isn't on the whitelist, so even though the "you are not allowed" error gets displayed, you can just navigate back to / and everything will work.

**Comment by sampsyo** [comment]
Ugh, security is hard! :fish:

I think you're right, and I don't know why that line was there in the first place.

Does this mean you've been getting the error message all along, and able to use the jasmine hooknook anyway? If so, can you please check that you're now correctly locked out, since the whitelist there just has me, @uwsampa, and @bholt right now? Then I can add you to the whitelist to let you in legit-like.

**Comment by jamesbornholt** [comment]
Yep, I was always able to use the jasmine hooknook, but I'm locked out now.

**Comment by sampsyo** [comment]
So embarrassed. :flushed: You should be good now.

**Comment by jamesbornholt** [comment]
Yep! Thanks! :see_no_evil:

**Comment by bholt** [comment]
Haha. :+1:
